# Generated by Django 3.2.3 on 2021-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=20)),
                ('img_cat', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mec', models.CharField(max_length=50, verbose_name='Nombre mecanico')),
                ('apellido_sol', models.CharField(max_length=20, verbose_name='Apellido mec')),
                ('descr_mec', models.TextField(blank=True, max_length=255, verbose_name='desc mec')),
                ('img_mec', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
