# Generated by Django 3.2.3 on 2021-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mecanico_img_mec'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='descr_mec',
            field=models.TextField(blank=True, max_length=255, verbose_name='desc mec'),
        ),
    ]
