# Generated by Django 3.2.3 on 2021-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210613_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='img_auto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
