# Generated by Django 3.2.3 on 2021-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_img_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=455),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo_auto',
            field=models.CharField(max_length=25, verbose_name='Modelo del Auto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='patente_auto',
            field=models.CharField(max_length=7, verbose_name='Patente'),
        ),
    ]
